server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5002/maintmanager_requests
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      connection-timeout: 30000
      max-lifetime: 2000000
