server:
  port: 8888

spring:
  profiles:
#    it means I want to read files from the file system
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/k.sichenko/Documents/projects/microservices/maint-manager-config-service/src/main/resources/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true